import prisma from "@/lib/prisma";
import { slugify } from "../src/lib/utils";
import { PricingType, Platform } from "@prisma/client";

async function main() {
  console.log("🌱 Starting seed...");

  // ─── Categories ──────────────────────────────────────────────────────────────
  const categoryData = [
    { name: "Writing", icon: "PenTool", color: "#6366f1", description: "AI writing assistants, content generators, and copywriting tools" },
    { name: "Coding", icon: "Code2", color: "#8b5cf6", description: "AI code assistants, debuggers, and developer tools" },
    { name: "Image Generation", icon: "Image", color: "#ec4899", description: "AI image generators, photo editors, and visual creation tools" },
    { name: "Video", icon: "Video", color: "#ef4444", description: "AI video generators, editors, and production tools" },
    { name: "Audio", icon: "Mic2", color: "#f59e0b", description: "AI voice generators, text-to-speech, and audio tools" },
    { name: "Music", icon: "Music", color: "#06b6d4", description: "AI music generation and composition tools" },
    { name: "Productivity", icon: "Zap", color: "#3b82f6", description: "AI productivity tools for work and organization" },
    { name: "Marketing", icon: "Share2", color: "#f97316", description: "AI marketing, advertising, and growth tools" },
    { name: "SEO", icon: "Search", color: "#84cc16", description: "AI SEO optimization and content strategy tools" },
    { name: "Research", icon: "Brain", color: "#a855f7", description: "AI research assistants and information gathering tools" },
    { name: "Education", icon: "GraduationCap", color: "#0ea5e9", description: "AI tutoring, learning, and educational tools" },
    { name: "Design", icon: "Palette", color: "#e879f9", description: "AI design tools for graphics, UI/UX, and visual content" },
    { name: "Chatbots", icon: "Bot", color: "#10b981", description: "AI chatbot builders and conversational AI platforms" },
    { name: "Automation", icon: "Layers", color: "#7c3aed", description: "AI workflow automation and process tools" },
    { name: "Data Analysis", icon: "BarChart3", color: "#64748b", description: "AI data analysis, visualization, and business intelligence" },
    { name: "Translation", icon: "Globe", color: "#2563eb", description: "AI translation and language learning tools" },
    { name: "PDF Tools", icon: "FileText", color: "#ca8a04", description: "AI PDF readers, summarizers, and document tools" },
    { name: "AI Agents", icon: "Cpu", color: "#059669", description: "Autonomous AI agents and task automation" },
    { name: "Presentation", icon: "Presentation", color: "#14b8a6", description: "AI presentation creators and slide design tools" },
    { name: "Resume", icon: "Briefcase", color: "#b45309", description: "AI resume writers and job application tools" },
    { name: "Social Media", icon: "Share2", color: "#0284c7", description: "AI social media content creation and management tools" },
    { name: "Healthcare", icon: "Heart", color: "#e11d48", description: "AI health and medical tools" },
    { name: "Legal", icon: "Scale", color: "#1d4ed8", description: "AI legal research and contract tools" },
    { name: "Finance", icon: "DollarSign", color: "#15803d", description: "AI financial analysis and planning tools" },
    { name: "Cybersecurity", icon: "Shield", color: "#dc2626", description: "AI security and threat detection tools" },
  ];

  const categories: Record<string, string> = {};
  for (const cat of categoryData) {
    const existing = await prisma.category.upsert({
      where: { slug: slugify(cat.name) },
      update: {},
      create: {
        name: cat.name,
        slug: slugify(cat.name),
        icon: cat.icon,
        color: cat.color,
        description: cat.description,
        featured: true,
      },
    });
    categories[cat.name] = existing.id;
    console.log(`✓ Category: ${cat.name}`);
  }

  // ─── Tags ─────────────────────────────────────────────────────────────────────
  const tagNames = [
    "AI Chat", "Writing", "Image AI", "Art", "Code", "IDE", "Editor",
    "Voice AI", "TTS", "Video AI", "Avatar", "Music AI", "Search", "Research",
    "Productivity", "Notes", "Web Dev", "Video Edit", "GPT", "Free", "API",
    "Open Source", "Business", "Students", "Developers", "Designers",
  ];

  const tags: Record<string, string> = {};
  for (const name of tagNames) {
    const tag = await prisma.tag.upsert({
      where: { slug: slugify(name) },
      update: {},
      create: { name, slug: slugify(name) },
    });
    tags[name] = tag.id;
  }

  // ─── AI Tools ─────────────────────────────────────────────────────────────────
  const toolsData = [
    {
      name: "ChatGPT",
      slug: "chatgpt",
      tagline: "The world's most popular AI chatbot for writing, coding, research, and more",
      description: "ChatGPT is an AI language model by OpenAI that can assist with a wide variety of tasks including writing, analysis, coding, math, and creative projects. It understands and generates human-like text, making it useful for students, professionals, and businesses alike.\n\nWith GPT-4o, ChatGPT can process images, voice, and code, making it the most versatile AI assistant available.",
      logo: "https://logo.clearbit.com/openai.com",
      website: "https://chat.openai.com",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 20,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.8,
      reviewCount: 2847,
      featured: true,
      trending: true,
      verified: true,
      platforms: ["WEB", "IOS", "ANDROID"] as Platform[],
      categoryName: "Writing",
      tagNames: ["AI Chat", "Writing", "GPT"],
      features: [
        "Advanced GPT-4o model",
        "Image understanding and generation",
        "Voice conversations",
        "Code generation and debugging",
        "DALL-E 3 image generation",
        "Custom GPTs (plugins)",
        "Web browsing",
        "File analysis",
      ],
      pros: [
        "Most capable AI model available",
        "Huge ecosystem of custom GPTs",
        "Multimodal (text, image, voice)",
        "Excellent at creative and analytical tasks",
      ],
      cons: [
        "Free tier has limitations",
        "Can hallucinate facts",
        "No real-time internet on free tier",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["GPT-3.5 access", "Limited GPT-4o", "Standard speed"] },
        { name: "Plus", price: 20, period: "month", features: ["GPT-4o access", "Priority speed", "Advanced features", "Custom GPTs"], highlighted: true },
        { name: "Team", price: 25, period: "month", features: ["Everything in Plus", "Admin controls", "Data privacy", "More usage"] },
      ],
      faqs: [
        { question: "Is ChatGPT free?", answer: "Yes, ChatGPT has a free tier. The paid ChatGPT Plus plan ($20/month) gives access to GPT-4o, faster responses, and additional features." },
        { question: "What can I use ChatGPT for?", answer: "Writing, coding, research, analysis, creative projects, math, language learning, summarization, and much more." },
      ],
    },
    {
      name: "Claude",
      slug: "claude",
      tagline: "Anthropic's AI assistant that's helpful, harmless, and honest",
      description: "Claude is an AI assistant built by Anthropic, focused on being safe, beneficial, and understandable. Claude 3.5 Sonnet is particularly strong at analysis, coding, and creative writing with a 200K context window.",
      logo: "https://logo.clearbit.com/anthropic.com",
      website: "https://claude.ai",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 20,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.7,
      reviewCount: 1234,
      featured: false,
      trending: true,
      verified: true,
      platforms: ["WEB", "API"] as Platform[],
      categoryName: "Writing",
      tagNames: ["AI Chat", "Writing"],
      features: [
        "200K token context window",
        "Strong at coding and analysis",
        "Artifacts (live preview)",
        "Document processing",
        "Computer use (beta)",
        "Vision capabilities",
      ],
      pros: [
        "Excellent for long documents",
        "More honest about limitations",
        "Great coding assistance",
        "Strong safety guardrails",
      ],
      cons: [
        "No image generation",
        "Limited free tier",
        "Fewer third-party integrations",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["Claude 3.5 Sonnet", "Limited messages"] },
        { name: "Pro", price: 20, period: "month", features: ["5x more usage", "Priority access", "Early features"], highlighted: true },
      ],
      faqs: [
        { question: "How is Claude different from ChatGPT?", answer: "Claude focuses more on safety and honesty, has a larger context window, and is often preferred for long document analysis and nuanced writing tasks." },
      ],
    },
    {
      name: "Midjourney",
      slug: "midjourney",
      tagline: "Create stunning AI-generated images from text descriptions",
      description: "Midjourney is an independent research lab that produces an AI program that creates images from natural language descriptions. Known for its artistic quality and aesthetic style, Midjourney is a favorite among designers, artists, and creative professionals.",
      logo: "https://logo.clearbit.com/midjourney.com",
      website: "https://midjourney.com",
      pricing: "PAID" as PricingType,
      startingPrice: 10,
      hasFreeTrial: false,
      hasApi: false,
      rating: 4.7,
      reviewCount: 1923,
      featured: true,
      trending: true,
      verified: true,
      platforms: ["WEB"] as Platform[],
      categoryName: "Image Generation",
      tagNames: ["Image AI", "Art"],
      features: [
        "V6.1 latest model",
        "Photo-realistic images",
        "Artistic style control",
        "Multiple aspect ratios",
        "Upscaling options",
        "Style reference images",
        "Character consistency",
        "Inpainting and variation",
      ],
      pros: [
        "Best aesthetic quality AI images",
        "Very active community",
        "Great for artistic creations",
        "Regular model updates",
      ],
      cons: [
        "No free tier",
        "Discord-based UI (can be complex)",
        "No API access",
        "Cannot generate text well",
      ],
      pricingPlans: [
        { name: "Basic", price: 10, period: "month", features: ["200 image generations/mo", "3 concurrent jobs"] },
        { name: "Standard", price: 30, period: "month", features: ["Unlimited relaxed generations", "15h fast GPU time"], highlighted: true },
        { name: "Pro", price: 60, period: "month", features: ["30h fast GPU time", "Stealth mode"] },
      ],
      faqs: [
        { question: "Does Midjourney have a free trial?", answer: "Midjourney removed its free trial. You need to subscribe to any paid plan starting at $10/month." },
      ],
    },
    {
      name: "GitHub Copilot",
      slug: "github-copilot",
      tagline: "AI pair programmer that helps you write better code faster",
      description: "GitHub Copilot uses the OpenAI Codex to suggest code and entire functions in real-time from your editor. It understands the context of your code and comments to provide relevant suggestions in dozens of programming languages.",
      logo: "https://logo.clearbit.com/github.com",
      website: "https://github.com/features/copilot",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 10,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.6,
      reviewCount: 1456,
      featured: true,
      trending: true,
      verified: true,
      platforms: ["WEB", "WINDOWS", "MAC", "LINUX", "CHROME_EXTENSION"] as Platform[],
      categoryName: "Coding",
      tagNames: ["Code", "IDE"],
      features: [
        "Inline code suggestions",
        "Multi-line completion",
        "Chat in IDE",
        "Supports 70+ languages",
        "Pull request summaries",
        "Code explanation",
        "Bug detection",
        "Test generation",
      ],
      pros: [
        "Deep IDE integration",
        "Excellent multi-language support",
        "Understands full project context",
        "Free for students & open source",
      ],
      cons: [
        "Requires IDE plugin",
        "Can suggest outdated patterns",
        "Privacy concerns with proprietary code",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["2000 completions/month", "50 chat messages"] },
        { name: "Individual", price: 10, period: "month", features: ["Unlimited completions", "Unlimited chat", "CLI tool"], highlighted: true },
        { name: "Business", price: 19, period: "month", features: ["Policy management", "Audit logs", "License management"] },
      ],
      faqs: [
        { question: "Is GitHub Copilot free for students?", answer: "Yes! Students and teachers with verified GitHub Education accounts get GitHub Copilot free of charge." },
      ],
    },
    {
      name: "Cursor",
      slug: "cursor",
      tagline: "The AI-first code editor built for pair programming with AI",
      description: "Cursor is an AI-first code editor that helps developers be more productive. Built on VS Code, it integrates AI directly into your coding workflow with features like codebase chat, AI-generated edits, and natural language commands.",
      logo: "https://logo.clearbit.com/cursor.sh",
      website: "https://cursor.sh",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 20,
      hasFreeTrial: true,
      hasApi: false,
      rating: 4.9,
      reviewCount: 1124,
      featured: true,
      trending: true,
      verified: true,
      platforms: ["WINDOWS", "MAC", "LINUX"] as Platform[],
      categoryName: "Coding",
      tagNames: ["Code", "IDE", "Editor"],
      features: [
        "Built on VS Code",
        "Codebase-aware chat",
        "Multi-file editing",
        "AI tab completion",
        "Natural language commands",
        "Composer for large changes",
        "Privacy mode",
        "Custom AI rules",
      ],
      pros: [
        "Fastest AI code editor",
        "VS Code compatible extensions",
        "Excellent codebase understanding",
        "Great for large refactors",
      ],
      cons: [
        "Paid features can be expensive",
        "Desktop only (no web)",
        "Consumes significant resources",
      ],
      pricingPlans: [
        { name: "Hobby", price: 0, period: "month", features: ["2000 completions", "50 slow premium requests"] },
        { name: "Pro", price: 20, period: "month", features: ["Unlimited completions", "500 fast premium requests", "Unlimited slow requests"], highlighted: true },
      ],
      faqs: [
        { question: "Is Cursor better than GitHub Copilot?", answer: "Cursor is often preferred for complex tasks requiring multi-file understanding, while Copilot integrates well into any IDE." },
      ],
    },
    {
      name: "ElevenLabs",
      slug: "elevenlabs",
      tagline: "Generative AI text to speech & voice cloning in 29 languages",
      description: "ElevenLabs creates the most realistic, versatile and contextually-aware AI speech software. Their voice cloning and text-to-speech technology is used by content creators, podcasters, publishers, and businesses worldwide.",
      logo: "https://logo.clearbit.com/elevenlabs.io",
      website: "https://elevenlabs.io",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 5,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.8,
      reviewCount: 892,
      featured: true,
      trending: true,
      verified: true,
      platforms: ["WEB", "API"] as Platform[],
      categoryName: "Audio",
      tagNames: ["Voice AI", "TTS"],
      features: [
        "Ultra-realistic TTS",
        "Voice cloning (3 min audio)",
        "29 language support",
        "Emotion control",
        "Real-time voice API",
        "Audio isolation",
        "Voice library (5000+ voices)",
        "Dubbing tool",
      ],
      pros: [
        "Most natural-sounding AI voices",
        "Excellent voice cloning",
        "Great API for developers",
        "Large voice library",
      ],
      cons: [
        "Free tier very limited (10K chars)",
        "Can be expensive at scale",
        "Voice quality varies by language",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["10,000 characters/mo", "3 custom voices"] },
        { name: "Starter", price: 5, period: "month", features: ["30,000 characters/mo", "10 custom voices", "Commercial license"] },
        { name: "Creator", price: 22, period: "month", features: ["100,000 characters/mo", "30 custom voices", "Priority processing"], highlighted: true },
      ],
      faqs: [
        { question: "Can ElevenLabs clone my voice?", answer: "Yes! ElevenLabs Instant Voice Cloning can clone a voice from as little as 1 minute of audio. Voice cloning requires a paid subscription." },
      ],
    },
    {
      name: "Runway",
      slug: "runway",
      tagline: "Next-generation AI creative tools for video generation and editing",
      description: "Runway is an applied AI research company shaping the next era of art, entertainment, and human creativity. Their Gen-3 Alpha model generates high-quality videos from text, images, and existing footage.",
      logo: "https://logo.clearbit.com/runwayml.com",
      website: "https://runwayml.com",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 15,
      hasFreeTrial: true,
      hasApi: false,
      rating: 4.5,
      reviewCount: 634,
      featured: true,
      trending: true,
      verified: true,
      platforms: ["WEB"] as Platform[],
      categoryName: "Video",
      tagNames: ["Video AI", "Art"],
      features: [
        "Gen-3 Alpha video model",
        "Text-to-video generation",
        "Image-to-video",
        "Video-to-video",
        "AI green screen",
        "Motion tracking",
        "Inpainting",
        "Multi-motion brush",
      ],
      pros: [
        "High quality video output",
        "Many creative AI tools in one",
        "Strong community",
        "Regular model updates",
      ],
      cons: [
        "Credits can run out fast",
        "Generated videos are short (4-10s)",
        "Expensive for heavy use",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["125 credits/mo", "720p output", "Watermark"] },
        { name: "Standard", price: 15, period: "month", features: ["625 credits/mo", "No watermark", "HD output"], highlighted: true },
        { name: "Pro", price: 35, period: "month", features: ["2250 credits/mo", "4K export", "Priority access"] },
      ],
      faqs: [],
    },
    {
      name: "Perplexity AI",
      slug: "perplexity-ai",
      tagline: "AI-powered search engine that answers any question with cited sources",
      description: "Perplexity AI is a conversational search engine that provides real-time, cited answers to any question. Unlike traditional search engines, it synthesizes information from multiple sources and presents it as a direct answer with references.",
      logo: "https://logo.clearbit.com/perplexity.ai",
      website: "https://perplexity.ai",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 20,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.6,
      reviewCount: 876,
      featured: false,
      trending: true,
      verified: true,
      platforms: ["WEB", "IOS", "ANDROID"] as Platform[],
      categoryName: "Research",
      tagNames: ["Search", "Research"],
      features: [
        "Real-time web search",
        "Cited sources",
        "Multi-model support (GPT-4, Claude)",
        "File upload analysis",
        "Spaces (collections)",
        "Focus modes (Academic, YouTube)",
        "Image generation",
      ],
      pros: [
        "Always up-to-date information",
        "Excellent citation system",
        "Great for research",
        "Fast and accurate",
      ],
      cons: [
        "Not as creative as pure LLMs",
        "Pro required for advanced models",
        "Sometimes misses context",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["Unlimited basic search", "5 Pro searches/day"] },
        { name: "Pro", price: 20, period: "month", features: ["600 Pro searches/day", "GPT-4, Claude access", "File uploads"], highlighted: true },
      ],
      faqs: [],
    },
    {
      name: "HeyGen",
      slug: "heygen",
      tagline: "Create AI avatar videos from text in minutes — no camera needed",
      description: "HeyGen is an AI video generation platform that helps businesses create professional videos with AI avatars. Used by Fortune 500 companies for training, marketing, and sales videos.",
      logo: "https://logo.clearbit.com/heygen.com",
      website: "https://heygen.com",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 29,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.4,
      reviewCount: 421,
      featured: false,
      trending: true,
      verified: true,
      platforms: ["WEB"] as Platform[],
      categoryName: "Video",
      tagNames: ["Video AI", "Avatar"],
      features: [
        "100+ AI avatars",
        "Video translation (40+ languages)",
        "Custom avatar creation",
        "Voice cloning",
        "Teleprompter mode",
        "Instant avatar (selfie)",
        "API for developers",
      ],
      pros: [
        "Fast video creation",
        "Professional-quality avatars",
        "Great translation features",
        "No camera required",
      ],
      cons: [
        "Free tier very limited (1 min video)",
        "Avatar lip sync can be off",
        "Expensive for high volume",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["1 credit/month", "720p export", "Watermark"] },
        { name: "Creator", price: 29, period: "month", features: ["15 credits/month", "1080p export", "No watermark"], highlighted: true },
        { name: "Business", price: 89, period: "month", features: ["30 credits/month", "Custom avatar", "API access"] },
      ],
      faqs: [],
    },
    {
      name: "Notion AI",
      slug: "notion-ai",
      tagline: "AI that works inside your Notion workspace for writing and analysis",
      description: "Notion AI is built directly into Notion and helps you write, edit, summarize, and brainstorm—all within your workflow. It can summarize meeting notes, draft documents, translate content, and more.",
      logo: "https://logo.clearbit.com/notion.so",
      website: "https://notion.so",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 10,
      hasFreeTrial: true,
      hasApi: false,
      rating: 4.4,
      reviewCount: 892,
      featured: false,
      trending: true,
      verified: true,
      platforms: ["WEB", "IOS", "ANDROID", "WINDOWS", "MAC"] as Platform[],
      categoryName: "Productivity",
      tagNames: ["Productivity", "Notes"],
      features: [
        "AI writing assistant",
        "Meeting summary",
        "Action item extraction",
        "Q&A over your workspace",
        "Translation",
        "Tone adjustment",
        "Brainstorming",
        "Autofill database properties",
      ],
      pros: [
        "Seamlessly integrated in Notion",
        "Great for teams",
        "Works on all your content",
        "Reasonable price",
      ],
      cons: [
        "Requires Notion subscription",
        "Limited to Notion ecosystem",
        "Less powerful than standalone AI",
      ],
      pricingPlans: [
        { name: "AI Add-on", price: 10, period: "month", features: ["Per workspace member", "Unlimited AI usage", "All AI features"], highlighted: true },
      ],
      faqs: [],
    },
    {
      name: "Suno AI",
      slug: "suno-ai",
      tagline: "Create full songs with AI — just describe the music you want",
      description: "Suno AI generates full songs complete with vocals, instruments, and lyrics from simple text prompts. Create professional-quality music in any genre in seconds, even with no musical experience.",
      logo: "https://logo.clearbit.com/suno.com",
      website: "https://suno.com",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 8,
      hasFreeTrial: true,
      hasApi: false,
      rating: 4.5,
      reviewCount: 543,
      featured: false,
      trending: true,
      verified: true,
      platforms: ["WEB"] as Platform[],
      categoryName: "Music",
      tagNames: ["Music AI"],
      features: [
        "Full song generation with lyrics",
        "Any genre support",
        "Custom style and mood",
        "Up to 2 minutes per song",
        "Extend existing songs",
        "Remix functionality",
        "Commercial license on paid plans",
      ],
      pros: [
        "Creates complete songs in seconds",
        "Impressive vocal quality",
        "Wide genre variety",
        "Easy to use",
      ],
      cons: [
        "Songs can sound similar at times",
        "Limited to ~2 min on free tier",
        "Commercial use requires paid plan",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["50 credits/day", "Non-commercial use", "Shared queue"] },
        { name: "Pro", price: 8, period: "month", features: ["2500 credits/month", "Commercial license", "Priority generation"], highlighted: true },
        { name: "Premier", price: 24, period: "month", features: ["10,000 credits/month", "All features"] },
      ],
      faqs: [],
    },
    {
      name: "Leonardo AI",
      slug: "leonardo-ai",
      tagline: "AI image generation platform for creatives and game developers",
      description: "Leonardo AI is a powerful AI art generation platform with fine-tuned models for game assets, illustrations, and photography. It offers advanced controls like ControlNet and a built-in canvas editor.",
      logo: "https://logo.clearbit.com/leonardo.ai",
      website: "https://leonardo.ai",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 12,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.5,
      reviewCount: 678,
      featured: false,
      trending: true,
      verified: true,
      platforms: ["WEB", "API"] as Platform[],
      categoryName: "Image Generation",
      tagNames: ["Image AI", "Art"],
      features: [
        "SDXL, Flux, Phoenix models",
        "ControlNet integration",
        "AI Canvas editor",
        "Motion generation (video)",
        "Real-time generation",
        "Model fine-tuning",
        "API access",
        "Background removal",
      ],
      pros: [
        "Generous free tier",
        "Game-focused models",
        "Advanced ControlNet",
        "Great API for developers",
      ],
      cons: [
        "Steeper learning curve",
        "Token-based system confusing",
        "UI can be overwhelming",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["150 tokens/day", "Public generations"] },
        { name: "Apprentice", price: 12, period: "month", features: ["8500 tokens/month", "Private generations", "API"], highlighted: true },
      ],
      faqs: [],
    },
    {
      name: "Jasper AI",
      slug: "jasper",
      tagline: "AI writing platform for marketing teams and content creators",
      description: "Jasper is an AI writing platform that helps marketing teams create on-brand content faster. With brand voice settings, templates, and campaign tools, it's designed for businesses producing content at scale.",
      logo: "https://logo.clearbit.com/jasper.ai",
      website: "https://jasper.ai",
      pricing: "PAID" as PricingType,
      startingPrice: 49,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.3,
      reviewCount: 567,
      featured: false,
      trending: false,
      verified: true,
      platforms: ["WEB", "CHROME_EXTENSION"] as Platform[],
      categoryName: "Writing",
      tagNames: ["Writing", "Business"],
      features: [
        "Brand voice settings",
        "80+ content templates",
        "Multi-language support",
        "SEO mode with Surfer",
        "Team collaboration",
        "Campaign creator",
        "Chrome extension",
        "AI image generation",
      ],
      pros: [
        "Great for brand-consistent content",
        "Many templates",
        "Team features",
        "Integrates with Surfer SEO",
      ],
      cons: [
        "Expensive starting price",
        "Output quality varies",
        "Not worth it for individuals",
      ],
      pricingPlans: [
        { name: "Creator", price: 49, period: "month", features: ["Single user", "1 brand voice", "AI chat"] },
        { name: "Pro", price: 69, period: "month", features: ["5 users", "3 brand voices", "SEO mode"], highlighted: true },
        { name: "Business", price: null, period: null, features: ["Custom users", "Unlimited brand voices", "API access"] },
      ],
      faqs: [],
    },
    {
      name: "Gemini",
      slug: "gemini",
      tagline: "Google's most capable AI model for text, code, images, and audio",
      description: "Gemini is Google's most capable and flexible AI model family. With Gemini Ultra, Pro, and Flash variants, it handles complex reasoning, coding, creative writing, and multimodal tasks. Deep Google Workspace integration makes it powerful for business users.",
      logo: "https://logo.clearbit.com/gemini.google.com",
      website: "https://gemini.google.com",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 20,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.5,
      reviewCount: 934,
      featured: false,
      trending: false,
      verified: true,
      platforms: ["WEB", "IOS", "ANDROID"] as Platform[],
      categoryName: "Writing",
      tagNames: ["AI Chat", "GPT"],
      features: [
        "Gemini 2.0 Flash and Ultra",
        "1M token context window",
        "Multimodal (text, image, audio, video)",
        "Google Workspace integration",
        "Code generation",
        "Real-time information",
        "Gemini Live (voice chat)",
      ],
      pros: [
        "Best Google ecosystem integration",
        "Very long context window",
        "Multimodal from the start",
        "Strong coding with code runner",
      ],
      cons: [
        "Less creative than GPT-4",
        "Workspace integration limits portability",
        "Image generation less impressive",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["Gemini 2.0 Flash", "Gemini in Gmail/Docs"] },
        { name: "Advanced", price: 20, period: "month", features: ["Gemini Ultra", "1M context", "Google One 2TB storage"], highlighted: true },
      ],
      faqs: [],
    },
    {
      name: "Descript",
      slug: "descript",
      tagline: "Edit audio and video by editing text — AI-powered media editing",
      description: "Descript is an all-in-one audio and video editing platform where you edit media by editing the transcript. Features like Overdub (AI voice cloning) and Studio Sound (audio enhancement) make it popular with podcasters and video creators.",
      logo: "https://logo.clearbit.com/descript.com",
      website: "https://descript.com",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 12,
      hasFreeTrial: true,
      hasApi: false,
      rating: 4.4,
      reviewCount: 423,
      featured: false,
      trending: false,
      verified: true,
      platforms: ["WEB", "WINDOWS", "MAC"] as Platform[],
      categoryName: "Audio",
      tagNames: ["Voice AI", "Video Edit"],
      features: [
        "Text-based video editing",
        "Auto-transcription",
        "AI voice clone (Overdub)",
        "Studio Sound (audio cleanup)",
        "Remove filler words",
        "Screen recording",
        "Podcast publishing",
        "Social clips AI",
      ],
      pros: [
        "Revolutionary text-based editing",
        "Great for podcasters",
        "Removes filler words",
        "Streamlined workflow",
      ],
      cons: [
        "Learning curve for video editors",
        "Not ideal for complex video edits",
        "AI voice quality variable",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["1 hour transcription", "Watermark", "720p export"] },
        { name: "Creator", price: 12, period: "month", features: ["10 hrs transcription", "No watermark", "4K export"], highlighted: true },
        { name: "Business", price: 24, period: "month", features: ["30 hrs transcription", "Overdub voice clone", "Team features"] },
      ],
      faqs: [],
    },
    {
      name: "Bolt.new",
      slug: "bolt-new",
      tagline: "Prompt, run, edit and deploy full-stack web apps with AI",
      description: "Bolt is an AI-powered web development platform that lets you create, edit, and deploy full-stack applications directly in the browser. Powered by Stackblitz WebContainers, it runs a full Node.js environment without any local setup.",
      logo: "https://logo.clearbit.com/bolt.new",
      website: "https://bolt.new",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 10,
      hasFreeTrial: true,
      hasApi: false,
      rating: 4.7,
      reviewCount: 567,
      featured: false,
      trending: true,
      verified: true,
      platforms: ["WEB"] as Platform[],
      categoryName: "Coding",
      tagNames: ["Code", "Web Dev"],
      features: [
        "Full Node.js environment",
        "Deploy to Netlify in one click",
        "Real-time preview",
        "GitHub integration",
        "Multiple framework support",
        "Database integration",
        "Environment variables",
        "NPM package support",
      ],
      pros: [
        "Complete app in minutes",
        "No local setup required",
        "Real full-stack apps",
        "Great for prototyping",
      ],
      cons: [
        "Token limits on free tier",
        "Complex apps hit limitations",
        "Cost adds up for large projects",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["150K tokens/day", "5 projects"] },
        { name: "Pro", price: 10, period: "month", features: ["Unlimited projects", "More tokens", "Priority access"], highlighted: true },
      ],
      faqs: [],
    },
    {
      name: "Canva AI",
      slug: "canva",
      tagline: "Design anything with AI — the world's most popular design tool",
      description: "Canva is an online design platform that has integrated powerful AI features. Magic Studio includes text-to-image, background remover, Magic Resize, and the AI presentation creator. Used by over 170 million people worldwide.",
      logo: "https://logo.clearbit.com/canva.com",
      website: "https://canva.com",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 15,
      hasFreeTrial: true,
      hasApi: false,
      rating: 4.6,
      reviewCount: 2134,
      featured: false,
      trending: false,
      verified: true,
      platforms: ["WEB", "IOS", "ANDROID"] as Platform[],
      categoryName: "Design",
      tagNames: ["Art", "Business"],
      features: [
        "Text to image (Magic Media)",
        "AI presentation creator",
        "Background remover",
        "Magic Resize",
        "Magic Eraser",
        "AI video generation",
        "Brand kit",
        "500K+ templates",
      ],
      pros: [
        "Extremely easy to use",
        "Huge template library",
        "All-in-one design tool",
        "Generous free tier",
      ],
      cons: [
        "Less control than Photoshop",
        "AI features require Pro",
        "Not for complex print design",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["250K+ templates", "5GB storage", "Basic tools"] },
        { name: "Pro", price: 15, period: "month", features: ["All AI features", "100GB storage", "Brand kit", "Premium content"], highlighted: true },
        { name: "Teams", price: 10, period: "month", features: ["Per person", "Team brand", "Admin controls"] },
      ],
      faqs: [],
    },
    {
      name: "Synthesia",
      slug: "synthesia",
      tagline: "Create professional AI videos with avatars — no camera or crew",
      description: "Synthesia is an AI video creation platform that lets you create professional videos with AI avatars in 130+ languages. Used by top companies for training videos, product demos, and employee communications.",
      logo: "https://logo.clearbit.com/synthesia.io",
      website: "https://synthesia.io",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 29,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.3,
      reviewCount: 312,
      featured: false,
      trending: false,
      verified: true,
      platforms: ["WEB"] as Platform[],
      categoryName: "Video",
      tagNames: ["Video AI", "Avatar", "Business"],
      features: [
        "160+ AI avatars",
        "130+ language support",
        "Custom avatar creation",
        "Screen recording",
        "Interaction (quizzes)",
        "Analytics",
        "API for automation",
      ],
      pros: [
        "Great avatar quality",
        "Best language support",
        "Ideal for L&D content",
        "Professional appearance",
      ],
      cons: [
        "Expensive for small teams",
        "Limited customization",
        "Avatars can look artificial",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["3 video exports", "9 AI avatars", "1 language"] },
        { name: "Starter", price: 29, period: "month", features: ["10 videos/mo", "90 avatars", "120 languages"], highlighted: true },
        { name: "Creator", price: 89, period: "month", features: ["30 videos/mo", "All features", "Custom avatar"] },
      ],
      faqs: [],
    },
    {
      name: "Copy.ai",
      slug: "copy-ai",
      tagline: "AI-powered copywriting for marketing teams and freelancers",
      description: "Copy.ai is an AI copywriting tool that helps marketers, entrepreneurs, and content creators produce high-quality marketing copy in seconds. It offers 90+ use-case templates and workflows for sales and marketing teams.",
      logo: "https://logo.clearbit.com/copy.ai",
      website: "https://copy.ai",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 36,
      hasFreeTrial: true,
      hasApi: false,
      rating: 4.2,
      reviewCount: 456,
      featured: false,
      trending: false,
      verified: true,
      platforms: ["WEB"] as Platform[],
      categoryName: "Writing",
      tagNames: ["Writing", "Business"],
      features: [
        "90+ templates",
        "Long-form content",
        "Sales copy",
        "Email sequences",
        "GTM (Go-to-market) workflows",
        "25+ languages",
        "Brand voice",
      ],
      pros: [
        "Great for marketing copy",
        "Many sales templates",
        "Good for beginners",
        "Free tier available",
      ],
      cons: [
        "Paid plans expensive",
        "Output needs editing",
        "Less powerful for long content",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["2000 words/month", "90+ templates", "1 user"] },
        { name: "Starter", price: 36, period: "month", features: ["Unlimited words", "5 users", "Workflows"], highlighted: true },
      ],
      faqs: [],
    },
    {
      name: "Grammarly",
      slug: "grammarly",
      tagline: "AI writing assistant that checks grammar, clarity, and tone",
      description: "Grammarly is an AI writing assistant that helps you write clearly and correctly. It checks for grammar, spelling, punctuation, clarity, tone, and plagiarism. Used by millions of students, professionals, and businesses.",
      logo: "https://logo.clearbit.com/grammarly.com",
      website: "https://grammarly.com",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 12,
      hasFreeTrial: true,
      hasApi: false,
      rating: 4.5,
      reviewCount: 3245,
      featured: false,
      trending: false,
      verified: true,
      platforms: ["WEB", "WINDOWS", "MAC", "IOS", "ANDROID", "CHROME_EXTENSION"] as Platform[],
      categoryName: "Writing",
      tagNames: ["Writing", "Students"],
      features: [
        "Grammar and spell check",
        "Clarity improvements",
        "Tone detection",
        "Plagiarism checker",
        "Generative AI writing",
        "Works in 500K+ apps",
        "Browser extension",
        "Microsoft Word plugin",
      ],
      pros: [
        "Works everywhere",
        "Easy to use",
        "Catches subtle grammar issues",
        "Great browser extension",
      ],
      cons: [
        "Full features require Premium",
        "Tone suggestions sometimes off",
        "Less useful for technical writing",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["Basic grammar check", "Tone detection", "150 AI prompts"] },
        { name: "Premium", price: 12, period: "month", features: ["Full grammar", "Clarity", "Plagiarism", "Unlimited AI"], highlighted: true },
        { name: "Business", price: 15, period: "month", features: ["Team management", "Style guides", "Billing control"] },
      ],
      faqs: [],
    },
    {
      name: "Ideogram",
      slug: "ideogram",
      tagline: "AI image generator that excels at text and typography in images",
      description: "Ideogram is an AI image generation tool particularly good at generating text within images — a major weakness of many other image AI tools. It's excellent for creating logos, posters, and social media graphics with text.",
      logo: "https://logo.clearbit.com/ideogram.ai",
      website: "https://ideogram.ai",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 7,
      hasFreeTrial: true,
      hasApi: false,
      rating: 4.3,
      reviewCount: 312,
      featured: false,
      trending: false,
      verified: true,
      platforms: ["WEB"] as Platform[],
      categoryName: "Image Generation",
      tagNames: ["Image AI", "Art"],
      features: [
        "Text rendering in images",
        "Ideogram 2.0 model",
        "Logo generation",
        "Poster design",
        "Style control",
        "Upscaling",
        "Edit and remix",
      ],
      pros: [
        "Best at text in images",
        "Great for logos and posters",
        "Good free tier",
        "Fast generation",
      ],
      cons: [
        "Less artistic than Midjourney",
        "Limited style variety",
        "API not publicly available",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["25 slow generations/day", "Public images"] },
        { name: "Basic", price: 7, period: "month", features: ["400 priority generations/mo", "Private images"], highlighted: true },
      ],
      faqs: [],
    },
    {
      name: "Otter.ai",
      slug: "otter-ai",
      tagline: "AI meeting assistant that records, transcribes, and summarizes meetings",
      description: "Otter.ai is an AI meeting assistant that automatically records audio, takes notes, captures slides, and generates meeting summaries. It integrates with Zoom, Google Meet, and Microsoft Teams.",
      logo: "https://logo.clearbit.com/otter.ai",
      website: "https://otter.ai",
      pricing: "FREEMIUM" as PricingType,
      startingPrice: 10,
      hasFreeTrial: true,
      hasApi: true,
      rating: 4.3,
      reviewCount: 723,
      featured: false,
      trending: false,
      verified: true,
      platforms: ["WEB", "IOS", "ANDROID"] as Platform[],
      categoryName: "Productivity",
      tagNames: ["Productivity"],
      features: [
        "Auto meeting transcription",
        "Meeting summary",
        "Action item extraction",
        "Slide capture",
        "Zoom/Meet/Teams integration",
        "Real-time captions",
        "Speaker identification",
        "Search transcripts",
      ],
      pros: [
        "Accurate transcription",
        "Automatic meeting summaries",
        "Cross-platform support",
        "Easy to share",
      ],
      cons: [
        "Free tier limited (300 min/month)",
        "Accuracy varies with accents",
        "Premium is pricey",
      ],
      pricingPlans: [
        { name: "Free", price: 0, period: "month", features: ["300 min/month", "Basic summaries"] },
        { name: "Pro", price: 10, period: "month", features: ["1200 min/month", "Advanced summaries", "Import audio"], highlighted: true },
        { name: "Business", price: 20, period: "month", features: ["6000 min/month", "Admin controls", "CRM integration"] },
      ],
      faqs: [],
    },
  ];

  for (const toolData of toolsData) {
    const {
      features, pros, cons, pricingPlans, faqs,
      categoryName, tagNames: toolTags,
      ...tool
    } = toolData;

    const categoryId = categories[categoryName];
    if (!categoryId) {
      console.warn(`Category not found: ${categoryName}`);
      continue;
    }

    const existing = await prisma.aITool.findUnique({ where: { slug: tool.slug } });
    if (existing) {
      console.log(`↩ Skipping existing tool: ${tool.name}`);
      continue;
    }

    const created = await prisma.aITool.create({
      data: {
        ...tool,
        categoryId,
        tags: {
          create: toolTags
            .filter((t) => tags[t])
            .map((t) => ({ tagId: tags[t] })),
        },
        features: {
          create: features.map((text, order) => ({ text, order })),
        },
        pros: {
          create: pros.map((text) => ({ text })),
        },
        cons: {
          create: cons.map((text) => ({ text })),
        },
        pricingPlans: {
          create: pricingPlans.map((plan) => ({
            ...plan,
            features: plan.features,
          })),
        },
        faqs: {
          create: faqs.map((faq, order) => ({ ...faq, order })),
        },
      },
    });

    console.log(`✓ Tool: ${created.name}`);
  }

  // Update category tool counts
  for (const [name, id] of Object.entries(categories)) {
    const count = await prisma.aITool.count({ where: { categoryId: id } });
    await prisma.category.update({ where: { id }, data: { toolCount: count } });
  }

  // ─── Collections ──────────────────────────────────────────────────────────────
  const collectionData = [
    {
      title: "Best Free AI Tools",
      slug: "best-free-ai-tools",
      description: "The best AI tools that are completely free or have a generous free tier.",
      emoji: "🆓",
      featured: true,
    },
    {
      title: "Best AI Tools for Students",
      slug: "ai-tools-for-students",
      description: "Research, writing, studying, and productivity tools for students.",
      emoji: "🎓",
      featured: true,
    },
    {
      title: "Best AI Coding Tools",
      slug: "ai-coding-tools",
      description: "Code faster, debug smarter, and ship better software with AI.",
      emoji: "💻",
      featured: true,
    },
  ];

  for (const col of collectionData) {
    await prisma.collection.upsert({
      where: { slug: col.slug },
      update: {},
      create: col,
    });
    console.log(`✓ Collection: ${col.title}`);
  }

  // ─── Workflows ─────────────────────────────────────────────────────────────────
  await prisma.workflow.upsert({
    where: { slug: "create-youtube-videos" },
    update: {},
    create: {
      title: "Create YouTube Videos with AI",
      slug: "create-youtube-videos",
      description: "A complete AI-powered workflow for creating YouTube videos from idea to upload",
      emoji: "🎬",
      featured: true,
    },
  });

  console.log("✅ Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
